"""empty message

Revision ID: 5693a41970f2
Revises: 
Create Date: 2023-05-15 23:46:38.231487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5693a41970f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=150), nullable=True),
    sa.Column('song', sa.String(length=150), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('peak', sa.String(length=3), nullable=True),
    sa.Column('weeks', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hit_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_hit_peak'), ['peak'], unique=False)
        batch_op.create_index(batch_op.f('ix_hit_song'), ['song'], unique=False)
        batch_op.create_index(batch_op.f('ix_hit_weeks'), ['weeks'], unique=False)
        batch_op.create_index(batch_op.f('ix_hit_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hit_year'))
        batch_op.drop_index(batch_op.f('ix_hit_weeks'))
        batch_op.drop_index(batch_op.f('ix_hit_song'))
        batch_op.drop_index(batch_op.f('ix_hit_peak'))
        batch_op.drop_index(batch_op.f('ix_hit_artist'))

    op.drop_table('hit')
    # ### end Alembic commands ###
